<?php
use Drupal\Core\Url;

/*
 * hook_toolbar()
 */
function la_admin_menu_toolbar() {
    global $base_url;
    
	// Appointment
    $menuAppointment = [
       'modules' => [
            'Manage Appointment'=>'appointments',
        ],
       'menuTitle' => 'Appointment System',
	   'subMenuTitle' => 'Appointments',
	   'uri' => $base_url.'/admin/',
	];
	$items['admin_menu_appointments'] = generateCustomAdminMenu($menuAppointment);
	
	// 
	
	/*
    $menuAbout = [
       'modules' => [
            'About'=>'about',
        ],
       'menuTitle' => 'About',
       'subMenuTitle' => 'About',
       'uri' => $base_url.'/admin/content-list/content_type/', 
	];
	$items['admin_menu_about'] = generateCustomAdminMenu($menuAbout);
	*/
	
	return $items;
}

function generateCustomAdminMenu ($customMenu ) {
    $modules = $customMenu['modules'];
    $menuTitle = $customMenu['menuTitle'];
    $subMenuTitle = $customMenu['subMenuTitle'];
    $uri = $customMenu['uri'];
    
    $links = array();
    $a=0;
    foreach ($modules as $module => $route) {
        $links[$module] = array(
            'title' => $module,
            'type'=>'link',
            'url' => Url::fromUri($uri.$route),
            'attributes' => array(
                'title' => $module,
            ),
        );
        $a++;
    }
    
    //content-list/{content_type}
    $shortcut_links = [
        '#theme'=>'links__toolbar_shortcuts',
        '#links'=>$links,
    ];
    
    // Create the examples toolbar render array.
    $items = array(
        '#type' => 'toolbar_item',
        'tab' => array(
            '#type' => 'link',
            '#title' => t($menuTitle),
            // @todo: Once it is created, use the example index page.
            '#url' => Url::fromRoute('<front>'),
            '#attributes' => array(
                'title' => t($subMenuTitle),
                'class' => array('toolbar-icon', 'toolbar-icon-examples'),
            ),
        ),

        'tray' => array(
            '#heading' => t($subMenuTitle),
            'shortcuts' => $shortcut_links,
        ),

        '#weight' => 200,
        '#attached' => array(
            'library' => array(
                'shortcut/drupal.shortcut',
            ),
        ),
    );
    
    return $items;
}