<?php

/**
 * @file
 * Contains flexgrid.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function flexgrid_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the flexgrid module.
    case 'help.page.flexgrid':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Bootstrap 3 UI for creating grids') . '</p>';
      return $output;

    default:
  }
}
