<?php
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function constant_contact_help ($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.loremipsum':
      return t('
          <h2>Constant Contact.</h2>
          <h3>Instructions</h3>
          <p>Help to manage constant contact API</p>
      ');
  }
}

/**
 * {@inheritdoc}
 */
function constant_contact_theme ($existing, $type, $theme, $path) {
    return [
        'custom_form_template' => [
            'render element' => 'form',
            'template' => 'custom-form-template',
        ],
    ];
}

/**
 * hook_form_alter().
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param string $form_id
 */
function constant_contact_form_constant_contact_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)  {
    $form['#theme'] = 'custom_form_template';
    $form['#attached']['library'][] = 'constant_contact/cc_libraries';
}